version: "3.5"

services:
  node:
    build: .
    platform: linux/x86_64
    container_name: sojourner-node
    volumes:
      - ./data:/root/.mars/data
      - ./secrets:/secrets
    ports:
      - '127.0.0.1:26657:26657'
      - '1317:1317'
      - '9093:9093'
    restart: unless-stopped